<!-- RSAM project code.
     Copyright (c) 2026 Daniel Riggi (riggi89).
     Attribution for modified SAM sources: LICENSE.md and NOTICE.md. -->

<Project>
  <PropertyGroup>
    <Version>1.0.28</Version>
    <AssemblyVersion>1.0.28</AssemblyVersion>
    <FileVersion>1.0.28</FileVersion>
    <Platforms>x86;x64</Platforms>
    <RSAMArchitecture Condition="'$(Platform)' == 'x86'">x86</RSAMArchitecture>
    <RSAMArchitecture Condition="'$(Platform)' == 'x64'">x64</RSAMArchitecture>
    <RSAMArchitecture Condition="'$(RSAMArchitecture)' == '' And '$(RuntimeIdentifier)' == 'win-x86'">x86</RSAMArchitecture>
    <RSAMArchitecture Condition="'$(RSAMArchitecture)' == '' And '$(RuntimeIdentifier)' == 'win-x64'">x64</RSAMArchitecture>
    <RSAMArchitecture Condition="'$(RSAMArchitecture)' == ''">x64</RSAMArchitecture>
    <PlatformTarget>$(RSAMArchitecture)</PlatformTarget>
    <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">win-$(RSAMArchitecture)</RuntimeIdentifier>
    <DefineConstants Condition="'$(RSAMArchitecture)' == 'x64'">$(DefineConstants);RSAM_X64</DefineConstants>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
</Project>
